version: "3"

services:

  # NFS Server
  nfs-server:
    image: itsthenetwork/nfs-server-alpine
    container_name: nfs-server
    hostname: nfs-s
    restart: always
    ports:
      - "2049:2049"
    volumes:
      - ./server/share:/nfsshare
    environment:
      - SHARED_DIRECTORY=/nfsshare
      # - READ_ONLY
      # - PERMITTED="10.11.99.*"
    cap_add:
      - SYS_ADMIN
      - SETPCAP

  nfs-client:
    image: d3fk/nfs-client
    container_name: nfs-client
    hostname: nfs-c
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SETPCAP