version: "3"

services:

  # NFS Server
  nfs-server:
    image: itsthenetwork/nfs-server-alpine
    container_name: nfs-server
    hostname: nfs
    restart: always
    ports:
      - "2049:2049"
    volumes:
      - ./server/share:/nfsshare
    environment:
      - SHARED_DIRECTORY=/nfsshare
      # - READ_ONLY
      # - PERMITTED="10.11.99.*"
    cap_add:
      - SYS_ADMIN
      - SETPCAP