version: "3"

networks:
  lab:
    ipam:
      config:
        - subnet: 10.0.103.0/24

services:
  # NFS Server
  server:
    image: erichough/nfs-server
    container_name: nfs-server
    hostname: server
    networks:
      lab:
        ipv4_address: 10.0.103.3    
    ports:
      - 2049:2049
    volumes:
      - ./server/exports.txt:/etc/exports:ro
      - ./server/share:/nfsshare
    cap_add:
      - SYS_ADMIN

  # Another NFS server image (unstable)
  server-2:
    image: itsthenetwork/nfs-server-alpine
    container_name: nfs-server
    hostname: server
    restart: always
    privileged: true
    networks:
      lab:
        ipv4_address: 10.0.103.23    
    ports:
      - 2049:2049
    volumes:
      - ./server/share:/nfsshare
    environment:
      - SHARED_DIRECTORY=/nfsshare
      - READ_ONLY
      - PERMITTED="10.0.103.*"
    cap_add:
      - SYS_ADMIN
      - SETPCAP


  client:
    build: ./client
    container_name: nfs-client
    hostname: nfs-c
    # net: host
    networks:
      lab:
        ipv4_address: 10.0.103.4
    privileged: true
    # restart: always
    # volumes:
      # - /mnt:/nfsshare:shared  
      # - ./demo:/nfsshare:shared   
    environment:
      SERVER: 10.0.103.3
      # - SHARE: 

  # nfs-client:
  #   image: d3fk/nfs-client
  #   container_name: nfs-client
  #   hostname: nfs-c
  #   privileged: true
  #   cap_add:
  #     - SYS_ADMIN
  #     - SETPCAP