version: "3.9"
services:
  nginx-lb:
    networks:
      - example
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/loadbalancer/include:/etc/nginx/include:ro
      - ./nginx/loadbalancer/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - www01
      - www02
    ports:
      - "80:80"
  www01:
    image: jmalloc/echo-server
    networks:
      - example
    ports:
      - "8080"
  www02:
    image: jmalloc/echo-server
    networks:
      - example
    ports:
      - "8080"

networks:
  example: