version: "3"

services:

  # DNS Server
  dns:
    image: internetsystemsconsortium/bind9:9.16
    container_name: dns-server
    hostname: bind9
    restart: always 
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "953:953/tcp"
    volumes:
      - ./conf/named.conf:/data/bind/etc/named.conf
      # - ./conf/named.conf.local:/data/bind/etc/named.conf.local
      # - ./conf/named.conf.options:/data/bind/etc/named.conf.options
      # - ./conf/named.conf.default-zones:/data/bind/etc/named.conf.default-zones
