version: "3"

networks:
  lab:
    ipam:
      config:
        - subnet: 10.0.103.0/24

services:
  # DNS Server
  dns:
    image: internetsystemsconsortium/bind9:9.16
    container_name: dns-server
    hostname: bind9
    restart: always 
    networks:
      lab:
        ipv4_address: 10.0.103.3
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./conf:/etc/bind/


  dns-secondary:
    image: internetsystemsconsortium/bind9:9.16
    container_name: dns-secondary
    hostname: bind9-sec
    restart: always 
    networks:
      lab:
        ipv4_address: 10.0.103.4
    ports:
      - "953:953/tcp"
      - "953:953/udp"
    volumes:
      - ./conf-secondary:/etc/bind/


  nsupdate:
    build: ./nsupdate
    container_name: nsupdate
    networks:
      lab:
        ipv4_address: 10.0.103.100
    volumes:
      - ./nsupdate/keys:/home/nsupdate/keys

  nsupdate2:
    image: menski/nsupdate
    container_name: nsupdate2
    networks:
      lab:
        ipv4_address: 10.0.103.101
    volumes:
      - ./nsupdate/keys:/keys

  dig:
    image: cmd.cat/dig/nslookup/whois
    container_name: dig
    networks:
      lab:
        ipv4_address: 10.0.103.200

