FROM alpine

ENV TERM xterm

ENV USER_UID 1000
ENV USER_NAME student
ENV USER_HOME /home/student

RUN apk update && \
    apk upgrade && \
    apk add --no-cache s-nail bash && \
    adduser -D -u $USER_UID $USER_NAME && \
    echo PS1=\"\\u@\\h:\\W \$ \" >> /root/.bashrc && \
    echo PS1=\"\\u@\\h:\\W \$ \" >> /$USER_NAME/.bashrc && \
    rm -rf /var/cache/apk/*

    