version: "3"

services:

  # Web service: Nginx:alpine
  webserver:
    image: nginx:alpine
    container_name: web-nginx
    hostname: web
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
    restart: unless-stopped
    tty: true
    volumes:
      - ./html:/usr/share/nginx/html/
      # - ./conf.d/:/etc/nginx/conf.d/
      # - ./html:/var/www/html/

  # Web service: Nginx
  webserver2:
    image: nginx
    container_name: web-nginx2
    hostname: web2
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
    environment:
     - NGINX_HOST=eureka.edu
     - NGINX_PORT=80
     - NGINX_PORT=8080
    restart: unless-stopped
    tty: true