version: "3"

services:

  # Web service: Nginx:alpine
  web-nginx:
    image: nginx:alpine
    container_name: web-nginx
    hostname: web
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
    restart: unless-stopped
    tty: true
    volumes:
      # mount the document root to be served
      # - ./conf.d/default:/etc/nginx/conf.d/default.conf
      - ./html/index.html:/usr/share/nginx/html/index.html
      # - ./html:/var/www/html/
      # mount the configuration folder or file
      - ./conf.d/ma.edu-8080:/etc/nginx/conf.d/ma-edu.conf
      - ./html/index-ma-edu.html:/var/www/html/index.html
      # - ./conf.d/ssl.conf:/etc/nginx/conf.d/ssl.conf
      

  # Web service: Nginx
  web-nginx2:
    image: nginx
    container_name: web-nginx2
    hostname: web2
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
    environment:
     - NGINX_HOST=eureka.edu
     - NGINX_PORT=80
     - NGINX_PORT=8080
    restart: unless-stopped
    tty: true