version: "3"

services:

  # Web service: Nginx:alpine
  web-nginx:
    image: nginx:alpine
    container_name: web-nginx
    hostname: web
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
    restart: unless-stopped
    tty: true
    volumes:
      # mount the document root to be served
      - ./html:/usr/share/nginx/html/
      # - ./html:/var/www/html/
      # mount the configuration folder or file
      # - ./conf.d/my-site:/etc/nginx/conf.d/sites-available/default
      # - ./conf.d/ssl.conf:/etc/nginx/conf.d/ssl.conf
      

  # Web service: Nginx
  web-nginx2:
    image: nginx
    container_name: web-nginx2
    hostname: web2
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
    environment:
     - NGINX_HOST=eureka.edu
     - NGINX_PORT=80
     - NGINX_PORT=8080
    restart: unless-stopped
    tty: true