version: "3"

services:

  # DHCP Server
  dhcp-server:
    image: networkboot/dhcpd
    container_name: dhcp-server
    hostname: dhcp-server
    ports:
      - "6767:67/udp"
    volumes:
      - "./server/conf/dhcpd.conf:/data/dhcpd.conf"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped


  # nmap
  nmap:
    image: instrumentisto/nmap
    container_name: nmap-dhcp-client


  # DHCP Client 
  dhclient:
    build: ./client
    container_name: dhcp-client
    hostname: dhcp-client
    restart: unless-stopped


