version: "3"


networks:
  lab:
    ipam:
      config:
        - subnet: 10.0.103.0/24

services:
  # DHCP Server
  dhcp-server:
    image: networkboot/dhcpd
    container_name: dhcp-server
    hostname: dhcp-server
    networks:
      lab:
        ipv4_address: 10.0.103.2
    # ports:
    #   - "6767:67/udp"
    volumes:
      - "./server/conf/dhcpd.conf:/data/dhcpd.conf"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped


  # nmap
  nmap:
    image: instrumentisto/nmap
    container_name: nmap-dhcp-client
    networks: 
      lab:


  # DHCP Client 
  dhclient:
    build: ./client
    container_name: dhcp-client
    hostname: dhcp-client
    restart: unless-stopped
    networks: 
      lab:

