version: "3"

services:

  # Web service: Apache auto configure with Dockerfile
  webserver:

    build:
      context: .
      dockerfile: Apache-Dockerfile

    container_name: web-apache
    hostname: web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped


  # Web service: Apache with manual configuration
  webserver2:
    image: httpd:2.4

    container_name: web-apache-2
    hostname: web2
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./html:/usr/local/apache2/htdocs/
      - ./conf/:/usr/local/apache2/conf/
