version: "3"

services:

  # Allow user to perform manual configuration
  # Configuration files are located in ./conf folder
  web-server-apache:
    # Instead of building an image, use a httpd image directly
    image: httpd:2.4
    container_name: web-apache
    hostname: web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./html:/usr/local/apache2/htdocs/
      - ./conf/:/usr/local/apache2/conf/


  # Apache configured with https enabled
  # using Dockerfile 
  web-https-apache:
    # Build our image based a Docker file
    build:
      context: .
      dockerfile: Apache-Dockerfile
    container_name: web-apache2
    hostname: web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

